---
# Shelly 2 Power Module
# Location: Upstairs Bathroom
#
substitutions:
  project: Upstairs Bathroom Fan
  id: shelly1_02
  humidity_difference_threshold: "10.0"   # 10% difference between house humidity and bathroom humidity.
  countdown_duration: "900"               # 900 seconds = 15 minutes

  <<: !include common/substitutions/gpio/shelly1.yaml

<<: !include common/esphome/esp8266.yaml
<<: !include common/common.yaml


binary_sensor:
  # Physical Toggle Switch. Monitor for switch position changes internally. Do not expose to Home Assistant.
  - platform: gpio
    pin:
      number: $button_gpio
    id: button
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_state:
      - switch.toggle: relay
      
      - text_sensor.template.publish:
          id: trigger
          state: PHYSICAL
      
      # Start the countdown timer.
      - if:
          condition:
            switch.is_on: relay
          then:
            - globals.set:
                id: remaining_time
                value: !lambda return $countdown_duration;
  
  #- platform: homeassistant
  #  entity_id: binary_sensor.upstairs_bathroom_humidity_decrease
  #  id: humidity_decrease_trend
  #  on_state:
  #    then:
  #      - lambda: |-
  #          if (id(humidity_difference).state < $humidity_difference_threshold) {
  #            id(relay).turn_off();
  #          }
  
  #- platform: homeassistant
  #  entity_id: binary_sensor.upstairs_bathroom_humidity_increase
  #  id: humidity_increase_trend
  #  on_state:
  #    then:
  #      # Turn the relay on.
  #      - switch.turn_on: relay
  #      
  #      - text_sensor.template.publish:
  #          id: trigger
  #          state: TREND

  # Use motion detection to keep fan running or turn it off when humidity isn't an issue.
  - platform: homeassistant
    id: motion
    entity_id: binary_sensor.upstairs_bathroom_motion
    on_state:
      then:
        if:
          # When motion is no longer detected.
          condition:
            binary_sensor.is_off: motion
          then:
            # Turn off the relay if the humidity difference is below the threshold.
            if:
              condition:
                sensor.in_range:
                  id: humidity_difference
                  below: $humidity_difference_threshold
              then:
                - switch.turn_off: relay
          # When motion is detected, and the fan is still on, extend the timeout timer.
          else:
            if:
              condition:
                switch.is_on: relay
              then:
                # Start the countdown timer over.
                - globals.set:
                    id: remaining_time
                    value: !lambda return $countdown_duration;

globals:
  - id: remaining_time
    type: int
    restore_value: no
    initial_value: "0"

# Update the countdown timers every 5 seconds.
interval:
  - interval: 5s
    then:
      #- logger.log: "5 seconds have passed."
      #- logger.log:
      #    format: "remaining_time: %s"
      #    args: ['id(remaining_time).state']
      
      - lambda: |-
          if (id(remaining_time) > 0) {
            // When the relay is on.
            if (id(relay).state) {
              // Decrement the timer.
              id(remaining_time) -= 5;

              // Turn off the relay when the time reaches zero... or the remaining time fails a sanity check!
              if (id(remaining_time) <= 0) {
                // Turn the relay off, unless someone is still present OR the humidity is higher than the threshold.
                if (
                    id(humidity_difference).state < $humidity_difference_threshold
                    or id(motion).state != true
                  ) {
                  id(relay).turn_off();
                  id(remaining_time) = 0;
                }
              }
            }
          }

sensor:
  # Measure the difference between the house humidity and bathroom humidity from Home Assistant.
  - platform: homeassistant
    id: humidity_difference
    entity_id: sensor.upstairs_bathroom_humidity_difference
    on_value_range:
      - above: $humidity_difference_threshold
        then:
          - switch.turn_on: relay
          
          - text_sensor.template.publish:
              id: trigger
              state: THRESHOLD
      - below: $humidity_difference_threshold
        then:
          - switch.turn_off: relay

switch:
  - platform: gpio
    id: relay
    pin: $relay_gpio
    #restore_mode: ALWAYS_OFF

  - platform: template
    name: $project
    optimistic: no
    lambda: |-
      if (id(relay).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: relay
      
      - text_sensor.template.publish:
          id: trigger
          state: VIRTUAL
      
      # Start the countdown timer.
      - globals.set:
          id: remaining_time
          value: !lambda return $countdown_duration;
    turn_off_action:
      - switch.turn_off: relay

text_sensor:
  # Trigger states: PHYSICAL, VIRTUAL (UI or Alexa), TREND, THRESHOLD
  - platform: template
    id: trigger
    name: "$project: Last Trigger"
   # lambda: return {""};

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time: 
      - seconds: 0
        minutes: /5
        then:
          # Every 5 minutes verify an automatically turned on fan is still above the humidity difference threshold.
          - if:
              condition:
                lambda:  |-
                  return (id(trigger).state == "TREND" || id(trigger).state == "THRESHOLD");
              then:
                - lambda: |-
                    if (id(humidity_difference).state < $humidity_difference_threshold) {
                      id(relay).turn_off();
                    }
